name: breaking_bad
description: "A Breaking Bad example using Nano."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  nano:
    path: ../../
  nano_annotations:
    path: ../../packages/nano_annotations
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  nano_generator:
    path: ../../packages/nano_generator
  nano_test_utils:
    path: ../../packages/nano_test_utils

flutter:
  uses-material-design: true
