name: nano_lints
description: Custom lints for the Nano state management library.
version: 0.0.2
environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  analyzer: ">=6.3.0 <9.0.0"
  custom_lint_builder: ">=0.6.4 <0.9.0"

dev_dependencies:
  custom_lint: ">=0.6.4 <0.9.0"
  lints: ^6.0.0
  test: ^1.24.0
