name: nano_lints
description: Custom lints for the Nano state management library.
version: 0.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=6.0.0 <9.0.0"
  custom_lint_builder: ^0.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
