name: nano_devtools_extension
description: A DevTools extension for the nano package.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.4.0
  devtools_app_shared: ^0.4.0
  nano:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
