name: example_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.27.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nano:
    path: ../../../
  nano_annotations:
    path: ../nano_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  nano_generator:
    path: ../nano_generator
