name: nano_generator
description: Code generator for Nano PoC.
version: 0.0.1
environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  build: ">=2.4.1 <5.0.0"
  source_gen: ">=1.4.0 <5.0.0"
  analyzer: ">=6.3.0 <9.0.0"
  nano_annotations: ^0.0.1
  code_builder: ^4.5.0
  dart_style: ">=2.3.2 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.6
